version: '3'
x-aws-vpc: "vpc-04126a79b32438b96"
services:
  candidate:
    image: 434874723296.dkr.ecr.us-east-1.amazonaws.com/candidate:latest
    build:
      context: ./candidate
      dockerfile: Dockerfile
    container_name: candidate
    ports:
      - 4001
    environment:
      - AWS_BUCKET_NAME=voter-attachements
      - AWS_BUCKET_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDQHW2IFC
      - AWS_SECRET_ACCESS_KEY=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
    restart: 'no'

  vote:
    image: 434874723296.dkr.ecr.us-east-1.amazonaws.com/vote:latest
    build:
      context: ./vote
      dockerfile: Dockerfile
    container_name: vote
    ports:
      - 8001
    environment:
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDQHW2IFC
      - AWS_SECRET_ACCESS_KEY=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
    restart: 'no'
