version: '3'
services:
  candidate:
    image: candidate
    build:
      context: ./candidate
      dockerfile: Dockerfile
    container_name: candidate
    ports:
      - 4001:80
    environment:
      - AWS_BUCKET_NAME=voter-attachements
      - AWS_BUCKET_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDQHW2IFC
      - AWS_SECRET_KEY=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
    restart: 'no'
