version: '3'
services:
  attachment-storage:
    image: attachment
    build:
      context: ./attachment
      dockerfile: Dockerfile-prod
    container_name: attachment-storage
    volumes:
      - /tmp/attachment/npm-cache:/root/.npm:z
      - ./attachment/src:/usr/src/app/src:z
    ports:
      - '4005:80'
    environment:
      - AWS_BUCKET_NAME=voter-attachements
      - AWS_BUCKET_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDQHW2IFC
      - AWS_SECRET_KEY=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
    restart: 'no'
