version: '3'
x-aws-vpc: 'vpc-06db8b0600a0cf70b'
services:
  candidate:
    image: 327006186574.dkr.ecr.ap-southeast-1.amazonaws.com/candidate:latest
    build:
      context: ./candidate
      dockerfile: Dockerfile
    container_name: candidate
    ports:
      - 4001:4001
    environment:
      - AWS_BUCKET_NAME=voteryak3bdpro-bucket
      - AWS_BUCKET_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAUYIYWNRHGBXUBDFP
      - AWS_SECRET_ACCESS_KEY=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
    restart: 'no'

  user:
    image: 327006186574.dkr.ecr.ap-southeast-1.amazonaws.com/user:latest
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user
    ports:
      - 5001:5001
    environment:
      - AWS_GATEWAY=https://l3rguk1msg.execute-api.ap-southeast-1.amazonaws.com/prod
      - AWS_API_KEY=HHKITwLzYU1lAwLNj1pO84fT3DBb4b1d4qOMPX0E
      - AWS_ACCESS_KEY_ID=AKIAUYIYWNRHGBXUBDFP
      - AWS_SECRET_ACCESS_KEY=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
    restart: 'no'

  vote:
    image: 327006186574.dkr.ecr.ap-southeast-1.amazonaws.com/vote:latest
    build:
      context: ./vote
      dockerfile: Dockerfile
    container_name: vote
    ports:
      - 6001:6001
    environment:
      - AWS_ACCESS_KEY_ID=AKIAUYIYWNRHGBXUBDFP
      - AWS_SECRET_ACCESS_KEY=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
      - USER_API_URL=http://http://micro-loadb-1sf89hgqxp9y1-fafd7045c7c83f11.elb.ap-southeast-1.amazonaws.com/:5001
      - CANDIDATE_API_URL=http://http://micro-loadb-1sf89hgqxp9y1-fafd7045c7c83f11.elb.ap-southeast-1.amazonaws.com/:4001
    restart: 'no'
    depends_on:
      - candidate
      - user
