version: '3'
x-aws-vpc: 'vpc-04126a79b32438b96'
services:
  candidate:
    image: 434874723296.dkr.ecr.us-east-1.amazonaws.com/candidate:latest
    build:
      context: ./candidate
      dockerfile: Dockerfile
    container_name: candidate
    ports:
      - 4001:4001
    environment:
      - AWS_BUCKET_NAME=voter-attachements
      - AWS_BUCKET_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDPLQRIMP
      - AWS_SECRET_ACCESS_KEY=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
    restart: 'no'

  user:
    image: 434874723296.dkr.ecr.us-east-1.amazonaws.com/user:latest
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user
    ports:
      - 5001:5001
    environment:
      - AWS_GATEWAY=https://o19hl9r57i.execute-api.us-east-1.amazonaws.com/prod
      - AWS_API_KEY=HHKITwLzYU1lAwLNj1pO84fT3DBb4b1d4qOMPX0E
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDPLQRIMP
      - AWS_SECRET_ACCESS_KEY=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
    restart: 'no'

  vote:
    image: 434874723296.dkr.ecr.us-east-1.amazonaws.com/vote:latest
    build:
      context: ./vote
      dockerfile: Dockerfile
    container_name: vote
    ports:
      - 6001:6001
    environment:
      - AWS_ACCESS_KEY_ID=AKIAWKQENVPQDPLQRIMP
      - AWS_SECRET_ACCESS_KEY=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
      - USER_API_URL=http://voter-loadb-fcubmgajq2kr-28cf2b9e5d7ff2ce.elb.us-east-1.amazonaws.com:5001
      - CANDIDATE_API_URL=http://voter-loadb-fcubmgajq2kr-28cf2b9e5d7ff2ce.elb.us-east-1.amazonaws.com:4001
    restart: 'no'
    depends_on:
      - candidate
      - user
